// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE-TgMEGZG8imQzoSplk2wcvPwaCoosR0',
    appId: '1:209941802246:web:a4d9d59baced1bccd78287',
    messagingSenderId: '209941802246',
    projectId: 'attend-app-e45a6',
    authDomain: 'attend-app-e45a6.firebaseapp.com',
    storageBucket: 'attend-app-e45a6.firebasestorage.app',
    measurementId: 'G-C0M7R664VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzfZFQZ5hJjsG0ozIyFEdxcJU2RKFugk',
    appId: '1:209941802246:android:c81fa08a80bf3408d78287',
    messagingSenderId: '209941802246',
    projectId: 'attend-app-e45a6',
    storageBucket: 'attend-app-e45a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYPy8zx6uO9jLoKsveKUVofiW-rJtyKU',
    appId: '1:209941802246:ios:49d6788fc67f36c8d78287',
    messagingSenderId: '209941802246',
    projectId: 'attend-app-e45a6',
    storageBucket: 'attend-app-e45a6.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYPy8zx6uO9jLoKsveKUVofiW-rJtyKU',
    appId: '1:209941802246:ios:49d6788fc67f36c8d78287',
    messagingSenderId: '209941802246',
    projectId: 'attend-app-e45a6',
    storageBucket: 'attend-app-e45a6.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE-TgMEGZG8imQzoSplk2wcvPwaCoosR0',
    appId: '1:209941802246:web:0e17ea4bcfdd64f5d78287',
    messagingSenderId: '209941802246',
    projectId: 'attend-app-e45a6',
    authDomain: 'attend-app-e45a6.firebaseapp.com',
    storageBucket: 'attend-app-e45a6.firebasestorage.app',
    measurementId: 'G-L2QT2P64ZK',
  );
}
